name       : qt6-remoteobjects
version    : 6.2.1
release    : 1
source     :
    - https://download.qt.io/official_releases/qt/6.2/6.2.1/submodules/qtremoteobjects-everywhere-src-6.2.1.tar.xz : 76681b03bb63e1cafa38a1bfde23c194f232aaff4b010d5f58c065fdcc0b379f
license    :
    - GFDL-1.3-or-later
    - GPL-2.0-or-later
    - LGPL-3.0-or-later
component  :
    - desktop.qt
    - demos : programming.library
summary    : Inter-process communication (IPC) module developed for Qt6
description: |
    Qt Remote Objects (QtRO) is an Inter-Process Communication (IPC) module developed for Qt. This module extends Qt's existing functionalities to enable information exchange between processes or computers, easily.
builddeps  :
    - pkgconfig(Qt6Qml)
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - devel :
        - /usr/lib64/qt6/mkspecs
    - demos :
        - /usr/lib64/qt6/examples
